# Generated by Django 5.2.8 on 2025-11-28 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEventWall', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('conferencia', 'Conferencia'), ('taller', 'Taller'), ('reunion', 'Reunión'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
