# Generated by Django 5.2.8 on 2025-11-28 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEventWall', '0004_comunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='appEventWall.comunidad'),
        ),
    ]
