# Generated by Django 5.2.8 on 2025-12-10 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEventWall', '0006_comunidad_miembros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='miembros',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que se han unido a la comunidad', related_name='comunidad_miembros', to=settings.AUTH_USER_MODEL),
        ),
    ]
