# Generated by Django 5.2.8 on 2025-12-11 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEventWall', '0007_alter_comunidad_miembros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='miembros',
            field=models.ManyToManyField(blank=True, related_name='miembro_de', to=settings.AUTH_USER_MODEL),
        ),
    ]
